### ISSUE TITLE
verify that pip install works correctly

### ISSUE THREAD

**Issue by yacosp** [okdana/jsonesque#1]
i tried to install jsonesque via pip yesterday for use in a personal project, but imports failed. moved it inside the projects' lib folder and it works ok. will add extra info to this issue later and, if possiblle, a solution.

**Comment by yacosp** [comment]
nevermind, it was just a ptpython install issue. btw: jsonesque works _perfectly_ 👍

**Comment by okdana** [comment]
Oh wow, i didn't know anybody used this package 😅

I was going to say, i tried installing it just now and it seemed OK. Thanks for the comments! Let me know if you have any other problems!

**Comment by yacosp** [comment]
i checked the alternatives, and most of them didn't handle trailing comments properly, or were overkill for my needs (just want to use commented .json files as configuration!). jsonesque is efficient and clean and does the job. good work!
